### ISSUE TITLE
Final "y" is wrong?

### ISSUE THREAD

**Issue by eddieantonio** [UAlbertaALTLab/nehiyawewin-syllabics#2]
I've been using ᕀ U+1540 CANADIAN SYLLABICS WEST-CREE Y as the final for Y, because... look at the name!

But I'm becoming increasingly convinced that the canoncical final should be ᐩ U+1429 CANADIAN SYLLABICS FINAL PLUS

I'm consistently told that ALL finals should be near the top, almost like a superscript. All fonts I'm aware of differs in rendering these two only by whether the final is to the side or to the side and near the top. ᐩ U+1429 CANADIAN SYLLABICS FINAL PLUS is always near the top, just like people keep telling me that final should go. So maybe _that_ should be my canonical choice for the Y final. I'd need to update `lookalikes.tsv`, and, of course, ensure all existing syllabics tools use this in the future:

 - [x] cree-sro-syllabics.py
 - [x] cree-sro-syllabics.js
 - [x] syllabics.app
 - [x] `nrc_crk_cans`
 - [ ] `fv_firstvoices`

I made a Twitter poll to try to figure it out: https://twitter.com/_eddieantonio/status/1275445947682545666

**Comment by aaronfay** [comment]
Just chiming in on this, I believe in Reubin's class he taught the opposite, that all 'consonant' syllabics are centered vertically. That the font used for Cree syllabics puts all the consonants at the top has always felt odd to me, since we were taught differently. 

It might be worth checking with Reubin Quinn and Jerry Saddleback (and maybe Les Skinner?) to see if they have any info/teachings around how the consonants are placed.

**Comment by eddieantonio** [comment]
hay-hay @aaronfay. I will check in with more writers. The concerning thing is that Unicode has this thing that really is a difference between fonts that is encoded as distinct characters. Bad Unicode!

**Comment by eddieantonio** [comment]
I think this has been resolved. ᐩ U+1429 CANADIAN SYLLABICS FINAL PLUS is the **correct** Y-final!

**Comment by aaronfay** [comment]
...for 80% of respondents ;) Might just have to chalk this one up to "regional variation".
